/**
 * BuscadorAutomovilesForm.java
 * 27 mar. 2023 16:11:35
 *
 */
package org.itson.presentacion;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.itson.dominio.Vehiculo;
import org.itson.dominio.Persona;
import org.itson.dominio.Placa;
import org.itson.servicio.PlacaServicio;
import org.itson.servicio.PersonaServicio;
import org.itson.servicio.VehiculoServicio;

/**
 * Descripción de la clase:
 *
 * @author Daniel Armando Peña Garcia ID:229185
 */
public class BuscadorAutomovilesForm extends javax.swing.JFrame {

    private PlacaServicio placaDAO;
    private PersonaServicio personaDAO;
    private VehiculoServicio vehiculoDAO;
    private SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
    private Persona persona;
    private Placa placaAnterior;
    private Vehiculo vehiculo;

    /**
     * Creates new form BuscadorAutomovilesForm
     */
    public BuscadorAutomovilesForm() {
        initComponents();
        this.placaDAO = new PlacaServicio();
        this.personaDAO = new PersonaServicio();
        this.vehiculoDAO = new VehiculoServicio();
        this.cargarTablaVehiculo();
        this.persona = new Persona();
        this.placaAnterior = new Placa();
        this.vehiculo = new Vehiculo();
    }

    public void cargarTablaVehiculo() {
        //List<Object[]> listaLotesPersonas = placaDAO.consultarPlacasPersonas();
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tblVehiculos.getModel();
        for (Object[] resultados : placaDAO.consultarPlacasPersonas()) {
            Calendar calendar = (Calendar) resultados[5];
            Date fecha = calendar.getTime();
            String fechaFormat = formatoFecha.format(fecha);
            resultados[5] = fechaFormat;
            modeloTabla.addRow(resultados);
        }
    }

    public void buscarPlacas() {

        DefaultTableModel modeloTabla = (DefaultTableModel) this.tblVehiculos.getModel();
        //Limpia tabla anterior
        modeloTabla.setRowCount(0);
//        String filtro = "numeroPlaca";
//        String busqueda = "";
//        if (this.txtPlacas.getText().trim() != "-") {
//            filtro = "numeroPlaca";
//            busqueda = this.txtPlacas.getText();
//        }
        for (Object[] resultados : placaDAO.consultarPlacasPersonasFiltro(this.txtPlacas.getText().trim())) {
            Calendar calendar = (Calendar) resultados[5];
            Date fecha = calendar.getTime();
            String fechaFormat = formatoFecha.format(fecha);
            resultados[5] = fechaFormat;
            modeloTabla.addRow(resultados);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        txtPlacas = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscador de Vehículos:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Placas: ");

        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Placa", "Placas", "Estado", "ID Vehiculo", "Número de Serie", "Fecha de Excepción", "ID Persona", "Nombre", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVehiculos);
        if (tblVehiculos.getColumnModel().getColumnCount() > 0) {
            tblVehiculos.getColumnModel().getColumn(0).setResizable(false);
            tblVehiculos.getColumnModel().getColumn(0).setPreferredWidth(35);
            tblVehiculos.getColumnModel().getColumn(1).setResizable(false);
            tblVehiculos.getColumnModel().getColumn(2).setResizable(false);
            tblVehiculos.getColumnModel().getColumn(3).setResizable(false);
            tblVehiculos.getColumnModel().getColumn(3).setPreferredWidth(110);
            tblVehiculos.getColumnModel().getColumn(4).setResizable(false);
            tblVehiculos.getColumnModel().getColumn(5).setResizable(false);
        }

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtPlacas.setBackground(new java.awt.Color(255, 255, 255));
        txtPlacas.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtPlacas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPlacas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        txtPlacas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlacasKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(txtPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addGap(93, 93, 93)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(143, 143, 143))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacasKeyTyped
        // TODO add your handling code here:
        this.buscarPlacas();
    }//GEN-LAST:event_txtPlacasKeyTyped

    private void tblVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehiculosMouseClicked
        // TODO add your handling code here:
        int seleccionar = tblVehiculos.rowAtPoint(evt.getPoint());
        String idString = String.valueOf(tblVehiculos.getValueAt(seleccionar, 6));
        Long idLong = Long.valueOf(idString);
        Persona personaSeleccionada = new Persona();
        personaSeleccionada.setIdPersona(idLong);
        this.persona = personaDAO.consultarPersona(personaSeleccionada);
        // JOptionPane.showMessageDialog(null, persona.toString());

        idString = String.valueOf(tblVehiculos.getValueAt(seleccionar, 0));
        idLong = Long.valueOf(idString);
        Placa placaSeleccionada = new Placa();
        placaSeleccionada.setIdTramite(idLong);
        this.placaAnterior = placaDAO.consultarPlaca(placaSeleccionada);
        // JOptionPane.showMessageDialog(null, placaAnterior.toString());

        idString = String.valueOf(tblVehiculos.getValueAt(seleccionar, 3));
        idLong = Long.valueOf(idString);
        Vehiculo vehiculoSeleccionado = new Vehiculo();
        vehiculoSeleccionado.setIdVehiculo(idLong);
        this.vehiculo = vehiculoDAO.consultarVehiculo(vehiculoSeleccionado);
        // JOptionPane.showMessageDialog(null, vehiculo.toString());
    }//GEN-LAST:event_tblVehiculosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        ActualizarPlacasForm actualizarPlacas = new ActualizarPlacasForm(persona, vehiculo, placaAnterior);
        this.dispose();
        actualizarPlacas.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVehiculos;
    private javax.swing.JFormattedTextField txtPlacas;
    // End of variables declaration//GEN-END:variables

}
