/**
 * SobreNosotrosDlg.java
 * 25 mar. 2023 14:28:23
 */
package org.itson.presentacion;

/**
 * Descripción de la clase:
 *
 * @author Daniel Armando Peña Garcia ID:229185
 */
public class NosotrosDlg extends javax.swing.JDialog {

    /**
     * Creates new form SobreNosotrosDlg
     */
    public NosotrosDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCuerpo = new javax.swing.JPanel();
        lblEquipo = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        lblMateria = new javax.swing.JLabel();
        lblNombreMateria = new javax.swing.JLabel();
        lblMaestro = new javax.swing.JLabel();
        lblNombreMaestro = new javax.swing.JLabel();
        panEncabezado = new javax.swing.JPanel();
        lblItson = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sobre Nosotros");

        panCuerpo.setBackground(new java.awt.Color(255, 255, 255));

        lblEquipo.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblEquipo.setForeground(new java.awt.Color(0, 102, 255));
        lblEquipo.setText("EQUIPO: ");

        lblNombre1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre1.setText("DANIEL ARMANDO PEÑA GARCÍA. ID: 229185");

        lblNombre2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblNombre2.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre2.setText("DANIEL OMAR ALAMEDA LÓPEZ.    ID: 228343");

        lblMateria.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblMateria.setForeground(new java.awt.Color(0, 102, 255));
        lblMateria.setText("MATERIA: ");

        lblNombreMateria.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblNombreMateria.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreMateria.setText("BASES DE DATOS AVANZADAS");

        lblMaestro.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblMaestro.setForeground(new java.awt.Color(0, 102, 255));
        lblMaestro.setText("MAESTRO: ");

        lblNombreMaestro.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblNombreMaestro.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreMaestro.setText("CHRISTIAN GIBRAN DURAN SOLANO");

        panEncabezado.setBackground(new java.awt.Color(0, 102, 255));

        lblItson.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        lblItson.setForeground(new java.awt.Color(255, 255, 255));
        lblItson.setText("ITSON");

        javax.swing.GroupLayout panEncabezadoLayout = new javax.swing.GroupLayout(panEncabezado);
        panEncabezado.setLayout(panEncabezadoLayout);
        panEncabezadoLayout.setHorizontalGroup(
            panEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblItson, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panEncabezadoLayout.setVerticalGroup(
            panEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblItson)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panCuerpoLayout = new javax.swing.GroupLayout(panCuerpo);
        panCuerpo.setLayout(panCuerpoLayout);
        panCuerpoLayout.setHorizontalGroup(
            panCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEquipo)
                    .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre2)
                    .addComponent(lblMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreMateria)
                    .addComponent(lblMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addComponent(panEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panCuerpoLayout.setVerticalGroup(
            panCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuerpoLayout.createSequentialGroup()
                .addComponent(panEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMaestro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreMaestro)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panCuerpo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEquipo;
    private javax.swing.JLabel lblItson;
    private javax.swing.JLabel lblMaestro;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombreMaestro;
    private javax.swing.JLabel lblNombreMateria;
    private javax.swing.JPanel panCuerpo;
    private javax.swing.JPanel panEncabezado;
    // End of variables declaration//GEN-END:variables

}
